[package]
name = "data_processing_rust"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.44.0", features = ["csv", "lazy"] }
serde = { version = "1.0", features = ["derive"] }

[dev-dependencies]
criterion = "0.4"